# `cargo fmt` configuration
# Docs: https://rust-lang.github.io/rustfmt/

edition = "2021"

max_width = 100                     # default is 80, async is more verbose so increasing this
hard_tabs = true
