FROM grafana/grafana-oss:13.0.2
COPY datasources.yml /etc/grafana/provisioning/datasources/datasources.yml
COPY dashboards.yml /etc/grafana/provisioning/dashboards/dashboards.yml
COPY dashboards /etc/grafana/provisioning/dashboards