# https://www.rabbitmq.com/docs/configure#config-items
management.load_definitions = /etc/rabbitmq/definitions.json
prometheus.tcp.port = 15692

default_user = $(RABBITMQ_DEFAULT_USER)
default_pass = $(RABBITMQ_DEFAULT_PASS)